version: '3'

services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'default'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD-SHELL', 'mysql --user=root --password=root -e "SHOW TABLES" default']
      interval: '5s'
      timeout: '1s'
      retries: 10
    volumes:
      - mysql_back_data:/var/lib/mysql
    networks:
      - mysql
  ms_back:
    build: .
    container_name: ms_back
    environment:
      SYMFONY_ENV: dev
#      ENABLE_XDEBUG: 1
    ports:
      - '8100:80'
    volumes:
      - '.:/var/www/html/src:rw'
    networks:
      - ms_back
      - mysql

networks:
  mysql: null
  ms_back: null

volumes:
  mysql_back_data:
    driver: local